# Generated by Django 3.2.9 on 2024-01-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('peso', models.FloatField(default=0)),
                ('masa', models.FloatField(default=0)),
                ('grasa', models.FloatField(default=0)),
                ('cintura', models.FloatField(default=0)),
                ('brazo', models.FloatField(default=0)),
                ('pierna', models.FloatField(default=0)),
                ('pecho', models.FloatField(default=0)),
                ('pecho_respirado', models.FloatField(default=0)),
                ('brazo_trabado', models.FloatField(default=0)),
                ('altura', models.FloatField(default=0)),
                ('edad', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
