# Generated by Django 3.2.9 on 2024-01-31 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=50)),
                ('grupo_a_ejercitar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejericio', models.CharField(max_length=50)),
                ('repeticiones', models.CharField(max_length=50)),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_gym.rutina')),
            ],
        ),
    ]
