# Generated by Django 3.2.9 on 2024-03-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_gym', '0003_rename_ejericio_ejercicio_ejercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TusRutinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(default=None, max_length=50)),
                ('grupo_a_ejercitar', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TusEjercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.CharField(default=None, max_length=50)),
                ('repeticiones', models.CharField(default=None, max_length=50)),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_gym.tusrutinas')),
            ],
        ),
    ]
