# Generated by Django 3.2.9 on 2024-03-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_gym', '0006_auto_20240301_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tusrutinas',
            name='grupo_id',
        ),
    ]
