# Generated by Django 3.2.9 on 2024-03-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_gym', '0008_auto_20240301_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRutinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tusrutinas',
            name='usuario',
        ),
    ]
