# Generated by Django 3.2.9 on 2024-03-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_gym', '0009_auto_20240301_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='tusrutinas',
            name='grupo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website_gym.usuariorutinas'),
            preserve_default=False,
        ),
    ]
