# Generated by Django 3.2.9 on 2024-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_gym', '0010_tusrutinas_grupo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tusrutinas',
            name='dias',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
